set nocompatible
syntax on
set termguicolors

" --- THE SECRET SAUCE ---
" This tells Vim: 'Don't use your own background color, use the Terminal's'
autocmd SourcePost * highlight Normal guibg=NONE ctermbg=NONE
autocmd SourcePost * highlight NonText guibg=NONE ctermbg=NONE

" UI Essentials
set number
set cursorline
