# Add this to the top of your .zshrc to cache completion results
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path "$HOME/.zcompcache"

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' menu select

eval "$(starship init zsh)"

alias update-install="~/dotfiles/scripts/update-install"
alias update-check="brew update && brew outdated; mas outdated; softwareupdate -l"
alias update-logs="sudo log stream --predicate 'process == \"softwareupdated\"' --level debug"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias zsh-reload="source ~/.zshrc && echo 'Zsh config reloaded!'"
alias sys="fastfetch"

# zsh plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-autopair/autopair.zsh

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/jchambers/.lmstudio/bin"
# End of LM Studio CLI section

